### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by gnovaro** [LeandroBarone/python-ascii_magic#2]
Traceback (most recent call last):
  File "convert.py", line 1, in <module>
    import ascii_magic
  File "/home/gustavo/.local/lib/python3.8/site-packages/ascii_magic/__init__.py", line 2, in <module>
    from PIL import Image, ImageGrab
  File "/usr/lib/python3/dist-packages/PIL/ImageGrab.py", line 26, in <module>
    raise ImportError("ImageGrab is macOS and Windows only")
ImportError: ImageGrab is macOS and Windows only

**Comment by LeandroBarone** [comment]
I just pushed an update that should fix the problem. Please reinstall the module with:

```pip install --upgrade --force-reinstall ascii_magic```

and try again.

**Comment by gnovaro** [comment]
Works!
